import Position from "../gameElements/position.js";
export const tileSheetPosList = [
    new Position(0, 2),
    new Position(4, 2),
    new Position(1, 2),
    new Position(3, 2),
    new Position(2, 2),
    new Position(3, 1),
    new Position(7, 1),
    new Position(4, 1),
    new Position(6, 1),
    new Position(5, 1),
    new Position(6, 0),
    new Position(2, 1),
    new Position(7, 0),
    new Position(1, 1),
    new Position(0, 1),
    new Position(-1, -1),
    new Position(-1, -1),
    new Position(3, 0),
    new Position(5, 0),
    new Position(4, 0),
    new Position(-1, -1),
    new Position(-1, -1),
    new Position(0, 0),
    new Position(2, 0),
    new Position(1, 0),
];
export const altTileSheetPosList = [
    new Position(4, 2),
    new Position(0, 2),
    new Position(3, 2),
    new Position(1, 2),
    new Position(2, 2),
    new Position(7, 1),
    new Position(3, 1),
    new Position(6, 1),
    new Position(4, 1),
    new Position(5, 1),
    new Position(2, 1),
    new Position(6, 0),
    new Position(1, 1),
    new Position(7, 0),
    new Position(0, 1),
    new Position(-1, -1),
    new Position(-1, -1),
    new Position(5, 0),
    new Position(3, 0),
    new Position(4, 0),
    new Position(-1, -1),
    new Position(-1, -1),
    new Position(2, 0),
    new Position(0, 0),
    new Position(1, 0),
];
